### ISSUE TITLE
seems doesn't support stage event

### ISSUE THREAD

**Issue by DophinL** [rafaesc/vue-konva#12]
I write:
`<v-stage ref="stage" @contentMousedown.proto="test" :config="configKonva">`

it would fail here

![image](https://user-images.githubusercontent.com/8707316/38765468-9f404a30-3ff4-11e8-91d0-fbcc8c8ff39e.png)

**Comment by Ldoppea** [comment]
Hi, I tried the code and I confirm it doesn't work, but I'm not sure how to use this kind of events.
cc @rafaesc

**Comment by rafaesc** [comment]
Seems that when you use an event with started with `content`, sends another object, without `target`, that I need to extract the component
https://github.com/konvajs/konva/blob/master/src/Stage.js#L501-L514

The good news that it was fixed, and also I took this feature to support event modifier
This issue: https://github.com/rafaesc/vue-konva/issues/4

Added a new example 
https://github.com/rafaesc/vue-konva/blob/master/examples/components/Circle.vue
[demo on live](http://rafaelescala.com/vue-konva/#/circle)

Regards!
