### ISSUE TITLE
Question: Use images

### ISSUE THREAD

**Issue by andrewhl** [rafaesc/vue-konva#17]
How would I use an image as a draggable object, as per this example:

https://konvajs.github.io/docs/drag_and_drop/Drag_an_Image.html

**Comment by andrewhl** [comment]
Checked `lib.js`, and noted that you provide an Image component (`v-image`), so I've answered my own question. That said, it would be very helpful if you could indicate on the docs all the Konva components you provide access to.

**Comment by Ldoppea** [comment]
Hi @andrewhl , the documentation is linked in the project description. Here is the link : http://rafaelescala.com/vue-konva-doc/

> All vue-konva components correspond to Konva components of the same name with the prefix 'v-'. All the parameters available for Konva objects can add as config in the prop for corresponding vue-konva components.
Core shapes are: v-rect, v-circle, v-ellipse, v-line, v-image, v-text, v-text-path, v-star, v-label, SVG Path, v-regular-polygon. Also you can create custom shape.

**Comment by andrewhl** [comment]
Ah, missed that. Thanks.
